### ISSUE TITLE
Broadcast RTMP stream to WebRTC peers

### ISSUE THREAD

**Issue by IamFake** [medooze/media-server#102]
Hi. Is it possible to take RTMP stream that could be attached to outgoingStream to webrtc peer?
I've test RTP -> WebRTC peer (broadcast.js in media-server-demo-node repo) and it works pretty well, but I don't get for now how to make a bridge between RTMP stream similarly. In that question I'm assume that both RTMP and WebRTC peer use h264 without sound (one-to-many-one-way broadcast scheme with low latency).

**Comment by murillo128** [comment]
check this:

https://www.npmjs.com/package/medooze-rtmp-server
