### ISSUE TITLE
SWIG go compiler issues with overloaded methods

### ISSUE THREAD

**Issue by murillo128** [medooze/media-server#105]
The Media Server for Golang has the issue, that the swig compiler can't compile the media server correctly. As a result, the support for pushing media streams was deactivated, which is a major turning point.

I have explained the problem in more detail here:
notedit/media-server-go-demo#30 (comment) 

https://github.com/medooze/media-server/pull/104

**Comment by marcelhencke** [comment]
Do you think this is an appropriate solution?

```
#ifndef SWIGGO
	// the SWIG compiler can not handle correctly the 2 GetData signatures for the GoLang target
	const BYTE* GetData() const		{ return buffer->GetData();			}
#endif
```

`SWIGGO` is only defined, when using SWIG and GoLang as target language. 
So there should be no conflict with other projects.

**Comment by murillo128** [comment]
this could be a temporary hack I could accept, i think best solution is to
rename some of the overloaded methods

**Comment by murillo128** [comment]
thanks! let me know if there is anything else needed!

**Comment by notedit** [comment]
cool,  I have came to this before.
