### ISSUE TITLE
 Video mixing with continuous presence

### ISSUE THREAD

**Issue by azzahrah** [medooze/media-server#108]
Iam new in video conferencing system, i want to know about this term:

" Video mixing with continuous presence" what this mean? i am so sorry for stupid question...

**Comment by sampleref** [comment]
Hope you have found the answer already, else here is a brief description https://www.ccexpert.us/video-conferencing/continuous-presence-conferences.html Basically it is 2 or more video tiles shown in a video conference system, rather than a single loudest/selected speaker

**Comment by azzahrah** [comment]
thank for information
