### ISSUE TITLE
Video codec H264 quality

### ISSUE THREAD

**Issue by pnkjvvdy** [medooze/media-server#15]
First sorry to create issue. Actually I want to clear my doubt but I don't found any place so I created issue.

Video codec H264 video quality is very poor with compare to VP8 codec. Also H264 codec use more CPU and memory with compare to VP8 still quality is poor.
I  also found that in this project FFMpeg library used for H264 decoding and x264 library used for encoding. So is there any licensing issue? May be quality reduced for this reason?

Is there any way to improve H264 video codec quality?

If I am calling Linphone 3.7.0 to Linphone 3.7.0 using H264 codec with resolution HD720p(1280x720) then video quality is good at both end. but If I join conference into media-server with same parameter then quality become poor. My mosaic size is also HD720p and I am using Mosaic1x1.

**Comment by murillo128** [comment]
sorry, but the open source version of the mcu is no longer maintained.
