### ISSUE TITLE
Compiling Media Mixer CentOS 7

### ISSUE THREAD

**Issue by klistrod** [medooze/media-server#16]
Hi Murillo,

I'm trying to compile lastest media mixer on CentOS 7 
All dependecies installed.
On step to compile media mixer the console show me the log errors:

`[CXX] release /usr/local/src/medooze/mcu/src/mcu.cpp
In file included from /usr/local/src/medooze/mcu/include/http.h:14:0,
                 from /usr/local/src/medooze/mcu/include/cpim.h:12,
                 from /usr/local/src/medooze/mcu/include/groupchat.h:13,
                 from /usr/local/src/medooze/mcu/include/multiconf.h:19,
                 from /usr/local/src/medooze/mcu/include/mcu.h:6,
                 from /usr/local/src/medooze/mcu/src/mcu.cpp:5:
/usr/local/src/medooze/mcu/include/stringparser.h: В функции-члене «virtual std::wstring JSONNumber::stringify()»:
/usr/local/src/medooze/mcu/include/stringparser.h:602:24: ошибка: вызов перегруженной функции **«abs(long double)»** неоднозначен
   if (abs(value-integer)<0.0000001)
                        ^
/usr/local/src/medooze/mcu/include/stringparser.h:602:24: замечание: candidates are:
In file included from /usr/local/src/medooze/mcu/src/mcu.cpp:1:0:
/usr/include/stdlib.h:770:12: замечание: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/include/c++/4.8.2/ext/string_conversions.h:41:0,
                 from /usr/include/c++/4.8.2/bits/basic_string.h:2815,
                 from /usr/include/c++/4.8.2/string:52,
                 from /usr/include/c++/4.8.2/stdexcept:39,
                 from /usr/include/c++/4.8.2/array:38,
                 from /usr/include/c++/4.8.2/tuple:39,
                 from /usr/include/c++/4.8.2/bits/stl_map.h:63,
                 from /usr/include/c++/4.8.2/map:61,
                 from /usr/local/src/medooze/mcu/src/mcu.cpp:2:
/usr/include/c++/4.8.2/cstdlib:174:3: замечание: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
/usr/include/c++/4.8.2/cstdlib:166:3: замечание: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^
make: *** [mcu.o] Ошибка 1`

problem in the function of abs as I understand:
`/usr/local/src/medooze/mcu/include/stringparser.h:602:24: ошибка: вызов перегруженной функции **«abs(long double)»** неоднозначен`

**Comment by murillo128** [comment]
Should be fixed now, thanks for the report!
