### ISSUE TITLE
xmlrpc server response shouldn't send transfer-encoding:chunked and length together

### ISSUE THREAD

**Issue by baiyufei** [medooze/media-server#19]
This is wireshark screenshot.
![wireshark](https://user-images.githubusercontent.com/14902592/38730015-94057ce2-3f47-11e8-9a8e-bcb1f32df518.png)

My node.js xmlrpc client reports error when receives response.

I change the code like this, then my node.js xmlrpc client works well.
https://github.com/medooze/media-server/blob/master/src/xmlrpcserver.cpp#L305

int XmlRpcServer::SendResponse(TSession *r, short code, const char *msg, int length)
{
	//Chunked output
	ResponseChunked(r);

	//POnemos el codigo
	ResponseStatus(r,code);

	//El content length
	// ResponseContentLength(r, length);

	//Escribimos la respuesta
	ResponseWriteStart(r);

	//La mandamos
	ResponseWriteBody(r,(char*)msg,length);

	//End it
	ResponseWriteEnd(r);

	return 1;
}

**Comment by murillo128** [comment]
thanxs, will try it and check if it is compatible with the mcu code

**Comment by murillo128** [comment]
I decided to change  the chunked piece, as the full length of the response is known beforehand.

**Comment by murillo128** [comment]
thanxs for the report!
