### ISSUE TITLE
logo.cpp

### ISSUE THREAD

**Issue by OlegIV1986** [medooze/media-server#23]
I'm trying to compile lastest media mixer on Ubuntu 16.04.
All dependecies installed.
On step to compile media mixer the console show me the log errors:

Code from https://svn.code.sf.net/p/mcumediaserver/code/trunk mcumediaserver-code

In file included from /usr/local/src/medooze/mcu/include/logo.h:6:0,
                 from /usr/local/src/medooze/mcu/src/logo.cpp:2:
/usr/local/include/libavcodec/avcodec.h:4400:6: note: declared here
 void av_free_packet(AVPacket *pkt);
      ^
/usr/local/src/medooze/mcu/src/logo.cpp:195:52: error: ‘FF_INPUT_BUFFER_PADDING_SIZE’ was not declared in this scope
  size = (((width/32+1)*32)*((height/32+1)*32)*3)/2+FF_INPUT_BUFFER_PADDING_SIZE+32;
                                                    ^
Makefile:254: ошибка выполнения рецепта для цели «logo.o»
make: *** [logo.o] Ошибка 1

**Comment by murillo128** [comment]
ffmpeg has renamed `FF_INPUT_BUFFER_PADDING_SIZE` as `AV_INPUT_BUFFER_PADDING_SIZE ` :

https://github.com/twitter/vireo/issues/11

You need to update ffmpeg to a newer version
