### ISSUE TITLE
Is this a little bug?

### ISSUE THREAD

**Issue by waterfoxfox** [medooze/media-server#24]
It is a  great open source project, thanks

Function:
                void AudioMixer::Process(DWORD numSamples) 
Code:
		//Clean rest
		memset(audio->buffer+audio->len,0,Sidebar::MIXER_BUFFER_SIZE-audio->len);
Should Be:
		memset(audio->buffer+audio->len,0, (Sidebar::MIXER_BUFFER_SIZE-audio->len)*sizeof(SWORD) );

**Comment by murillo128** [comment]
good catch!

**Comment by murillo128** [comment]
thanxs for the report!
