### ISSUE TITLE
Wrong FPU period checking when receiving video

### ISSUE THREAD

**Issue by baiyufei** [medooze/media-server#35]
https://github.com/medooze/media-server/blob/master/src/videostream.cpp#L760
https://github.com/medooze/media-server/blob/master/src/videostream.cpp#L677

`if (listener && getDifTime(&lastFPURequest)>minFPUPeriod)`

**getDifTime** returns microseconds, and the unit of **minFPUPeriod** is milliseconds.

Probably missing " **/1000** " like this.

https://github.com/medooze/media-server/blob/master/src/videostream.cpp#L444
`if (getDifTime(&lastFPU)/1000>minFPUPeriod)`

**Comment by murillo128** [comment]
Thank you!
