### ISSUE TITLE
create other language wrappers of media-server

### ISSUE THREAD

**Issue by notedit** [medooze/media-server#37]
Hi @murillo128 

I am using your  media-server-node lib,  and it works well.  but  still  have other issue when using  the node lib.  for example,  media-server can use multi threads,  but node can only use one thread,  and  node is not a good choice to handle media stuff(media mux/demux,  media transcode).   I am thinking create a golang wrapper of media-server.   

What do you think about this?

**Comment by murillo128** [comment]
I don't have enough bandwidth for that at the moment but in theory it should be possible, as I am using swig to expose the c++ stuff into node, and swig supports go:
http://www.swig.org/compat.html

It will require to rewrite all the js layer that is on the /lib directory.

**Comment by notedit** [comment]
I will give that a try and let you know.

**Comment by notedit** [comment]
Start working on it  https://github.com/notedit/media-server-go,  but still need a sdp parser

**Comment by notedit** [comment]
@murillo128   hi  i  can use swig generate the cpp files, and then build the static libmediaserver.a 
but when go build,  there is a build error,  i searched  hours,  but still can not figure it out.
I do not if you can give me some help.

the error is  like  
```
# _/Users/xiang/Work/RTCEngine/media-server-go
ld: library not found for -l/Users/xiang/Work/RTCEngine/media-server-go/mediaserver/bin/debug/libmediaserver.a
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
# _/Users/xiang/Work/RTCEngine/media-server-go
In file included from mediaserver_wrap.cxx:363:
./mediaserver/include/mp4streamer.h:66:11: warning: enumeration value 'Unknown' not handled in switch [-Wswitch]
mediaserver_wrap.cxx:483:12: warning: enumeration value 'Unknown' not handled in switch [-Wswitch]
```

it seems that  cgo can not works well with static libs.

**Comment by notedit** [comment]
https://github.com/notedit/media-server-go

wow,  just make the base test pass.   if anyone  is  interested in it,  you can have a  try.

**Comment by murillo128** [comment]
Awesome work @notedit!
