### ISSUE TITLE
Performance of Meida Server

### ISSUE THREAD

**Issue by shailesh-panchal** [medooze/media-server#60]
Hi All,

Could any one has performance testing number of Media server which give us the number like how many concurrent HD conference / Stream can process by at same time.

Regards,
shailesh

**Comment by murillo128** [comment]
You area asking for the MCU?

**Comment by shailesh-panchal** [comment]
Yes I am asking of MCU performance testing data.

**Comment by murillo128** [comment]
The cpu usage in MCU is mainly due to the video encoding process, which depends on the image size and codec.

Typical figures are 1 participant in  720P participant and VP8 per cpu core, 3 participants in VGA and 4 in H264 VGA.
