### ISSUE TITLE
Mac os does support  IP_MTU_DISCOVER IP_PMTUDISC_DO 

### ISSUE THREAD

**Issue by notedit** [medooze/media-server#61]
the latest commit broken mac os build

**Comment by murillo128** [comment]
is `pthread_setaffinity_np` available on mac?

**Comment by notedit** [comment]
macos  does not support `pthread_setaffinity_np`  too.

**Comment by murillo128** [comment]
I was looking at the same link.. :)

also some more background info:
https://developer.apple.com/library/archive/releasenotes/Performance/RN-AffinityAPI/

**Comment by murillo128** [comment]
not sure how to restore affinity to THREAD_AFFINITY_NULL

**Comment by murillo128** [comment]
let's move to it's own issue
