### ISSUE TITLE
pthread_setaffinity_np  not available on mac

### ISSUE THREAD

**Issue by murillo128** [medooze/media-server#63]
Fork of #61 

macos does not support pthread_setaffinity_np too. see https://yyshen.github.io/2015/01/18/binding_threads_to_cores_osx.html

also some more background info:
https://developer.apple.com/library/archive/releasenotes/Performance/RN-AffinityAPI/

**Comment by murillo128** [comment]
@notedit could you check latest commit? I

**Comment by notedit** [comment]
```
../media-server/src/EventLoop.cpp:61:11: error: use of undeclared identifier
      'thread_policy_set'
                return !thread_policy_set(pthread_mach_thread_np(thread....
                        ^
../media-server/src/EventLoop.cpp:63:101: error: use of undeclared identifier
      'THREAD_AFFINITY_NULL'
  ...THREAD_AFFINITY_POLICY, THREAD_AFFINITY_NULL, 1);

```

**Comment by notedit** [comment]
I just check the  `/usr/include/mach/thread_policy.h`,      `thread_policy_set` is commented.

**Comment by murillo128** [comment]
https://lists.apple.com/archives/darwin-kernel/2014/Nov/msg00003.html

**Comment by murillo128** [comment]
can you check latest commit?

**Comment by notedit** [comment]
Yes, latest commit works.

**Comment by murillo128** [comment]
pitt is that mac does not allow to set thread affinity to an specific thread, but just create affinity groups which is not exactly the same.. but at leas you poor mac users have it compiling.. 😂
