### ISSUE TITLE
SSL_clear in dtls.cpp

### ISSUE THREAD

**Issue by baiyufei** [medooze/media-server#68]
https://github.com/medooze/media-server/blob/master/src/dtls.cpp#L816

```
if (SSL_clear(ssl)==0)
    Error("-DTLSConnection::Write() | SSL_clear() failed: %s", ERR_error_string(ERR_get_error(), NULL));
ssl = nullptr;
```

ssl will be set to nullptr after SSL_clear. There is no chance to call SSL_free on ssl. 

Could there be a memory leak?

**Comment by murillo128** [comment]
Thank you!

**Comment by baiyufei** [comment]
https://github.com/medooze/media-server/blob/master/src/dtls.cpp#L627
https://github.com/medooze/media-server/blob/master/src/dtls.cpp#L816

@murillo128 
In my test case, there is a chance to call  DTLSConnection::Read after this SSL_free(). DTLSConnection::Read function will use write_bio(related to dlts) which has been freed. I test with ASAN, so here can be crush. 

I Check the dtls is null or not at the beginning of the DTLSConnection::Read. My test is based on version of last year, and I don't know this issue and change still be suitable.

Thank you!

**Comment by murillo128** [comment]
umm.. i might overlooked it.

Bestis just don't do anything on shutdown and on the near future raise and event to the app so it can close it, what do you think?

**Comment by baiyufei** [comment]
I don't know much ssl, but I think you're right.

I will close this.
