### ISSUE TITLE
waitingForIntra in *LayerSelector will cause subscriber can't receive any video data

### ISSUE THREAD

**Issue by vvspacetime** [medooze/media-server#72]
When call RTPStreamTransponder::SetIncoming, the media server will sendPLI to publisher. But if the Intra Frame is lost, the subscriber can't receive any data(even P Frame) until the publisher send next Intra Frame, because of the "waitingForIntra".  It maybe cause subsciber can't watch video for 5-10 minutes.

**Comment by murillo128** [comment]
what client are you using for subscribing? all webrtc browsers will periodically request PLI if there is no data received, that's why I don't implement PLI retransmission on the media server

**Comment by vvspacetime** [comment]
I use chrome74.0.3729.169. If it don't receive any data, it can't send pli request. I have used wireshark to verify it.

**Comment by vvspacetime** [comment]
Thank you. I'll wait for your reply.

**Comment by murillo128** [comment]
thanks for reporting this!
