### ISSUE TITLE
How to build the Project?

### ISSUE THREAD

**Issue by MrsZ** [medooze/media-server#8]

**Comment by primoitt83** [comment]
Hello there,

I think one of my guides could help you.

Check it out!

Ubuntu 16.04
https://docs.google.com/document/d/15fa4aV_0_TX27Uje0XwwOPf5qobZUfakj4nchXrlYdw/edit

Centos 7
https://docs.google.com/document/d/1q4aFgk2DYhZmB_rwo61fq1Nsihne7Fz1jUNb5sBZdKc/edit?usp=sharing
