### ISSUE TITLE
NACK optimize

### ISSUE THREAD

**Issue by notedit** [medooze/media-server#80]
Hi murillo,

I read your nack part code,  i think the nack can be optimized.  here is some stats from webrtc.
I test this in local network.

this is  retransmit bitrate
<img width="354" alt="Screen Shot 2019-09-30 at 2 35 26 PM" src="https://user-images.githubusercontent.com/480864/65854897-59a08a80-e390-11e9-8ae3-d2c4c4e15d49.png">

this is video bitrate 
<img width="338" alt="Screen Shot 2019-09-30 at 2 36 13 PM" src="https://user-images.githubusercontent.com/480864/65854951-7d63d080-e390-11e9-81db-b582511ce4ae.png">

this is nack received
<img width="344" alt="Screen Shot 2019-09-30 at 2 36 34 PM" src="https://user-images.githubusercontent.com/480864/65854968-8785cf00-e390-11e9-9133-5535e312cf68.png">

**Comment by murillo128** [comment]
How do you think it can be optimized? i am against early-optimizations without clear metrics from real live scenarios.

**Comment by murillo128** [comment]
Also, what do you see wrong in your graphics?

**Comment by notedit** [comment]
I  compare  medooze  and  agora's  service on my mac,   agora's  has very little nacks and  retransmit bitrate is almost is zero.

**Comment by notedit** [comment]
> Also, what do you see wrong in your graphics?

the nacks is too much and  the retransmit bitrate is a bit of high.

**Comment by murillo128** [comment]
do you have a sendonly stream? in this case I use rtx/nacks to get the rtt periodically. If not, there should be nacks according to the packet losses.

**Comment by notedit** [comment]
yes,  this is a sendonly stream.  I know you send rtx to get rtt periodically,   but there is only one rtx in one second.

**Comment by murillo128** [comment]
nack policy is a bit aggressive, I send one nack packet each time a packet is lost and on subsequent packets until rtx is received or timeout happens.

This nacks redundant packets will be filtered by libwebrtc and only send rtx first time the nack packet is receveid and retransmisión based on rtt. So this causes no extra rtx from client->server.

The only effect are minor spikes of rtcp traffics depending on the rtt which should not have much side issues.

**Comment by notedit** [comment]
Just go through  webrtc's nack_module   https://github.com/notedit/webrtc-clone/blob/5a29d526be7589f5ba7fb824a749f9088b305070/modules/video_coding/nack_module.cc#L36

they add a  default 10ms  delay  filter.   that may help.

**Comment by notedit** [comment]
I think  we can add a delay of jitter.

**Comment by notedit** [comment]
I have a simple test for  in my local,  add 20ms delay  can  reduce half of  retransmit bitrate  in 500kbps.

**Comment by murillo128** [comment]
that's expected as bbr is a delay based algorithm so an increase means
congestion and bwe is reduced.

post a screenshot of the bwe stats viewer to set the behavior of the
algorithm better

**Comment by notedit** [comment]
We may not say the same thing, I mean the  incoming source's RTPLostPackets,

I add a  20ms filter when generate nacks,  filter the pakcets's time is less than (now - 20ms).

**Comment by murillo128** [comment]
not sure if i follow you,  could you share pr and test case?

also that 20ms should be dependent of the rtt, not a fixed value

**Comment by notedit** [comment]
Ok,  Will give a pr when i have more free time.
