### ISSUE TITLE
MP4Recoder maybe can not work

### ISSUE THREAD

**Issue by vvspacetime** [medooze/media-server#82]
When I test mp4record, I found it can not work. When check it stack as follow
![image](https://user-images.githubusercontent.com/20473768/67660462-cca21e80-f999-11e9-987b-25357665f26e.png)
StreamTrackDepacketizer::onRTP should have called MP4Recorder::onMediaFrame. But it call MP4Recorder::Stop method actually. I think it is a Virtual Function Pointer error. So I change MP4Recorder inheritance order, put the `public MediaFrame::Listener` before `public RecorderControl`. Now it worked, and I record success.
Environment: I compile and run in mac.

**Comment by murillo128** [comment]
Could you recompile and try again with latest version please?
