### ISSUE TITLE
When ontargetbitrate callback, the persistent had been released

### ISSUE THREAD

**Issue by vvspacetime** [medooze/media-server#85]
This problew will cause coredump. We catch the corefile, as shown as follow.
![image](https://user-images.githubusercontent.com/20473768/69332603-0103b480-0c92-11ea-9b14-3506bea157c8.png)
![image](https://user-images.githubusercontent.com/20473768/69332630-0bbe4980-0c92-11ea-8db3-d846ef3e9daf.png)

**Comment by murillo128** [comment]
which media server version are you using, this doesn't match latest code:

https://github.com/medooze/media-server-node/blob/master/src/media-server.i#L681

**Comment by murillo128** [comment]
note how I clone the shared::ptr containing the persistent object to prevent the issue that you are describing. Can you double check?

**Comment by vvspacetime** [comment]
I check my version in package.json, and this is 0.79.0 that after your modify about clone. I think maybe v8 engine recycle this object, but c++ shared_ptr can't know.

**Comment by murillo128** [comment]
the code on the backtrace doesn't match which latest code. Check if the
source code on your server matches the backtrace one or not. If it
doesn't,  you are running a different version.

**Comment by vvspacetime** [comment]
sorry, it is my fault

**Comment by murillo128** [comment]
no problem, anyway it is great news that you can go into that level on detail when troubleshooting an issue, that helps me a lot!
