### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by Jeevhi** [medooze/media-server#91]
Sergio, I am unable to reopen previous issue and hence creating new. More compilation errors:

```
[CXX] debug /code/media-server/src/AudioCodecFactory.cpp
In file included from /code/media-server/include/audio.h:4,
                 from /code/media-server/include/AudioCodecFactory.h:3,
                 from /code/media-server/src/AudioCodecFactory.cpp:2:
/code/media-server/include/media.h:9:10: fatal error: Buffer.h: No such file or directory
 #include "Buffer.h"
          ^~~~~~~~~~
```
I could not find Buffer,h in the code.  Not sure if this requires some dependent packages but they are not mentioned. 

```
[root@dell-idc11 media-server]# find . -name "[Bb]uffer.h"
[root@dell-idc11 media-server]# 

```

**Comment by murillo128** [comment]
You need to init the git submodules
```
git submodule update --init --recursive
```

**Comment by Jeevhi** [comment]
Ok I figured that, further errors

[CXX] debug /code/media-server/src/AudioCodecFactory.cpp
In file included from /code/media-server/src/AudioCodecFactory.cpp:4:
/code/media-server/src/gsm/gsmcodec.h:2:10: fatal error: gsm.h: No such file or directory
 #include "gsm.h"
          ^~~~~~~
compilation terminated.

**Comment by Jeevhi** [comment]
Could you keep this issue open please

**Comment by murillo128** [comment]
http://medooze.com/products/media-mixer-server/installation.aspx

**Comment by Jeevhi** [comment]
excellent, looking into

**Comment by edwar64896** [comment]
OK I am in the same boat here. I have initialised submodules but still missing this header file.
