### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by Finichek** [medooze/media-server#99]
Hello, readme file says that the media-server can be used under the MIT License in case of usage under the Medooze Media Server Node. Yet the project only contains GPL license in the license file itself. Is it a mistake?

Could you please confirm that it is possible to use medooze-server-node under MIT license and that it supersedes the GPL-2.0 requirements of the medooze media server?

**Comment by murillo128** [comment]
Yes, that is correct. Media server used inside medooze-server-node is MIT as the GPL parts of libavcodec are not used there.
